### ISSUE TITLE
problem when it convert to Slic3r

### ISSUE THREAD

**Issue by jheduart** [ra100/curaToSlic3rProfile#3]
I use the profile file that is in the test folder: curaM3dAbs.ini
![image](https://cloud.githubusercontent.com/assets/6516044/18420573/3691ef0c-783b-11e6-8a67-ba68c0fd3ff6.png)

**Comment by ra100** [comment]
fixed by 89568b03f65e3d661d127a6521f37b392723329a
I am sorry, I've forgotten to push latest changes.

**Comment by jheduart** [comment]
Great, it's working ok, thanks you so much!!
